stages:
  load_data:
    cmd: python src/load_data.py --config=param.yaml
    deps:
    - src/load_data.py
    - src/get_data.py
    - data_given/winequality.csv
    outs:
    - data/raw/winequality.csv