base:
  project:  winequality-project
  random_state: 42
  target: TARGET

data_source:
  s3_source: data_given/winequality.csv

load_data:
  raw_dataset: data/raw/winequality.csv

split_data:
    test_path: data/processed/test_data.csv
    train_path: data/processed/train_data.csv
    test_size: .2
 
estimator:
  Random_forest_regressor:
    params:
      n_estimators: 20
      random_state: 0

model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json